### ISSUE TITLE
Some log files only keep 1 record in the file

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#1018]
All log files except the error.log file seems to only contain 1 record which gets overwritten when ever a new record gets added.

The error.log does add it's records to the end of the file when COM_errorLog is used, so it looks like something is happening in the log class.

**Comment by eSilverStrike** [comment]
@mystralkk I also notice that the new downsload.log file doesn't contain a time stamp anymore since the switch to its own log file.

How do you want to handle this? It would be nice for plugins (and easier to read) to use the same formats available to the core plugins but I notice each plugin is hardcoded into the class. Should we add a flag to the common function that would automatically add the

timestamp and/or remote ip and/or username

to the beginning of the log entry if set?

**Comment by mystralkk** [comment]
As for timestamp, I would change so that Log::__callStatic() will automatically prepend it onto log entries.  As for remote IP, username and user ID, I would change so that Log::__callStatic() will accept as an element of its second argument (array) like Log::downloads($entry, 'rin'), 'r' for remote IP address, 'i' for user ID, and 'n' for user name respectively.  If the second argument is omitted, then we assume 'rin' is specified.  What do you think of this?

**Comment by eSilverStrike** [comment]
Sounds good.

**Comment by mystralkk** [comment]
Fixed with change set b2d8957.
