### ISSUE TITLE
Trying to upgrade from 2.2.0 to 2.2.1 fails with InnoDB when database character set is 'utf8mb4'

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#1027]
```
Fatal error: 1071: Specified key was too long; max key length is 1000 bytes in path\to\geeklog\system\databases\mysqli.class.php on line 468
```
SQL in question is:
```
$sql = "ALTER TABLE gl_topic_assignments
   DROP PRIMARY KEY,
   ADD PRIMARY KEY( `tid`, `type`, `subtype`, `id`);
";
```
4 * (75(`tid`) + 30(`type`) + 30(`subtype`) + 128( `id`)) = 1052

**Comment by mystralkk** [comment]
@eSilverStrike,  is it acceptable to change the length of `subtype` from 30 to 15?

**Comment by mystralkk** [comment]
I wondered why this error doesn't happen on fresh install and now understand the reason. The `topic_assignments` table is defined as:
```
CREATE TABLE `{$_TABLES['topic_assignments']}` (
  `tid` varchar(75) NOT NULL,
  `type` varchar(30) NOT NULL,
  `subtype` varchar(15) NOT NULL DEFAULT '',
  `id` varchar(128) NOT NULL,
  `inherit` tinyint(1) NOT NULL default '1',
  `tdefault` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`tid`,`type`,`id`)
```
Look at PRIMARY KEY and you see it consists of `tid`,`type`,`id`, while on upgrade it is changed to consist of `tid`, `type`, `subtype`, `id`.  Which is right?

**Comment by eSilverStrike** [comment]
Good catch.

- tid needs to match topic id which is 75
- type needs to match length of plugin name which is 30
- id is used obviously to identify a plugins item and in most cases these ids are 128 characters or shorter
- subtype is used by plugins to internally identify items. Plugins may have more than 1 item type they may want to apply a topic to. For example the forum plugin has forum categories and forum posts

Subtypes don't have to be 30 I just made them that way to match the plugin type length. Still with the orignal primary key we are almost maxed out. Technically the primary key should be
ADD PRIMARY KEY( `tid`, `type`, `subtype`, `id`);
as we don't want duplicates of the above. Since we cannot do this should we keep it 
ADD PRIMARY KEY( `tid`, `type`, `id`);
and rely on the Topics Editor to ensure that (`tid`, `type`, `subtype`, `id`) doesn't exist more than once?

I don't like it but it's not like we don't do this else where since our table structures don't use foreign keys.

The new likes table also uses a similar structure but does not have a proper primary key since that would include almost all of the  columns in the table. If we change the subtype length it would need to be changed on the likes table as well.

**Comment by eSilverStrike** [comment]
Hmm, looking at my development server the topic_assignments table which is InnoDB has the primary key of PRIMARY KEY( tid, type, subtype, id); with the subtype column of 30. I guess this depends on the version of MySQL and is the reason why I didn't notice the problem. I also didn't have an issue with it when upgrading Geeklog.net

**Comment by eSilverStrike** [comment]
I updated the primary key for the topic assignments table to be just ( tid, type, id) since it is not possible with our minimum requirements MySQL requirements to have (tid, type, subtype, id). 

Does that sound good?

**Comment by mystralkk** [comment]
I don't think it is a good idea to exclude subtype field from the primary key, since it could cause inconsistency.  As I first wrote, why don't we change the length of subtype from 30 to 15?

**Comment by eSilverStrike** [comment]
Oh yes that is fine, my mistake. When I did the calculation before with 15 I got over 1000 for some reason. I will update the code and reduce the size of the subtype and fix the primary key
