### ISSUE TITLE
Downloads install in error

### ISSUE THREAD

**Issue by remyKobolski** [Geeklog-Core/geeklog#1109]
After installing the downloads plugin (tried multiple), trying to add a category:

`E_WARNING(2) - move_uploaded_file(/home/pbsolo/php7/downloads_data/category_snaps/Glossary.gif): failed to open stream: No such file or directory @ /home/pbsolo/_php7_/plugins/downloads/include/functions.php line 457
`

First the warning  irritates because it suggests that the signature of move_uploaded_file is incorrect.
That, the upload directory is NOT `<public_html>/downloads_data`, neither it is `<private_site>/downloads_data`.
It is installed as `<private_site>/plugins/downloads/downloads_data`.

This is not funny, since I don't know what a correct configuration should be:

> Should downloads_data be in some other place, or is functions.php buggy?

And ..... shouldn't this failure be caught?

**Comment by eSilverStrike** [comment]
Hi,

The downloads plugin has its own repository:

https://github.com/Geeklog-Plugins/downloads

along with its own issue tracker:

https://github.com/Geeklog-Plugins/downloads/issues

BTW most non-core plugins have their own repository which can be found here:https://github.com/Geeklog-Plugins

Since it is not possible for me to transfer this issue can you recreate at the above link if more help is needed (or if you want to reply to this thread).

It looks like you might not have moved the downloads_data directory, did you do step 6 in the install (found in install.txt)?

Step 6:  Upgrades can skip this step. For new installs, from the path.to.geeklog/plugins/downloads/ directory copy the directory downloads_data into the public_html/ directory.  IMPORTANT: Set directory permission so that your webserver has write access to this directory and all sub directories. This may require write permissions to be 744, 754 or 777 depending on your webserver setup.

**Comment by remyKobolski** [comment]
Ooh, shame on me. I’ve overlooked step 6.
Pls. close the issue.

Remy
