### ISSUE TITLE
[Feature Requests] Convert all references of Story to Article

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#423]
**Reported by @eSilverStrike  on 29 Jan 2011 22:19**

**Version:** 1.8.0

**Description:**
We call posts both stories and articles. Since article.php name needs to stay the same (or all links to articles would be broken) it has been decided that all story references need to be changed to article.

This includes in the Language Files and for things like the configuration, story editor, and search.

This also includes file names/directories (and references to those files)
- \system\lib-story.php 
- \system\classes\story.class.php
- \public_html\admin\story.php
- \public_html\layout\professional\storybodytext.thtml
- \public_html\layout\professional\storytext.thtml
- \public_html\layout\professional\admin\story
- \public_html\layout\professional\admin\story\storyeditor.thtml
- \public_html\layout\professional\admin\story\storyeditor_Advanced.thtml

and probably a few more I missed.

[Mantis Bugtracker #1263](http://project.geeklog.net/tracking/view.php?id=1263)

**Comment by mystralkk** [comment]
I tried working on this issue, but gave up in the end because there are so many places to change that I am not sure how far I should change.

**Comment by eSilverStrike** [comment]
Yeah this is a difficult one to figure out how far to go.

We also have to consider backwards compatibility. (like keeping the story autotag but also adding an article autotag)

I was thinking when I made this request was the file names as described above and any place where a user interaction with articles happens (that it calls story or stories). For example the Advance Search list of Types says Stories instead of Articles. A lot of these changes would hopefully be just language variables.

I wasn't thinking really of changing any internal code and variable or function names that references Story instead of Article. That would be a lot of work and a lot of testing. We could go this far but at the moment I don't think it is worth the time.

**Comment by mystralkk** [comment]
Okay, I tried again and finished converting with change set f9e6183.  I didn't change API names including 'story' nor did I change table names.
