### ISSUE TITLE
[Feature Requests] Add an option to not log IP addresses

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#438]
**Reported by @dhaun on 26 Feb 2011 14:28**

**Version:** 1.7.2

**Description:**
In some jurisdictions, IP addresses are considered "personal data" and subject to special handling.

As a first measure, we should have an option to disable logging of IP addresses entirely. Since we can't control what 3rd party plugins are doing, we should even consider overwriting $_SERVER["REMOTE_ADDR"].

Since IP addresses are useful to track down and fight abuse and spam, we should later look into having an option to delete the IP address after a configurable time, e.g. 48 hours.

**Additional Information:**
Specifically: In Germany, courts have ruled IP addresses to be sensitive data that may not be stored, other than for strictly necessary operational purposes. And even then, you are only allowed to store them for a reasonably short time.

Google Analytics and similar services seem to get away with "anonymizing" the IP address by masking the lower 8 bits.

[Mantis Bugtracker #1281](http://project.geeklog.net/tracking/view.php?id=1281)

**Comment by eSilverStrike** [comment]
Old and/or outdated issue so closing. If you feel this issue should have stayed open then comment below with your reasons.

**Comment by eSilverStrike** [comment]
It would be difficult to delete IP addresses after X hours... especially since they can be stored in databases and log files where a last modified date may not be available for the record. Also what happens if the IP is used as an ID for the record?

I think the easiest way to deal with this is have a config option to allow IP recording or not. We then can create a class for Geeklog that handles IPs which Geeklog and plugins are required to use. If a feature requires an IP address then it will have to be disabled (or a work around figured out). Geeklog could also check to see if plugins are compliant or not (by adding some sort of API check) and use the new Geeklog IP class and issue a warning if not to the Admin in the Plugin Manager (and on save of the config option).

So where does Geeklog store IP address? Off the top of my head I remember Log files, Poll plugin, speedlimit, spamx, ... probably other spots as well.

**Comment by mystralkk** [comment]
> It would be difficult to delete IP addresses after X hours... especially since they can be stored in databases and log files where a last modified date may not be available for the record. Also what happens if the IP is used as an ID for the record?

> I think the easiest way to deal with this is have a config option to allow IP recording or not.

I agree.

> So where does Geeklog store IP address? Off the top of my head I remember Log files, Poll plugin, speedlimit, spamx, ... probably other spots as well.

Plus staticpages, COM_applyBasicFilter, COM_handle404, Likes, PingBack, TrackBack, Session, reCAPTCHA, Links, comments, lib-webservice, downloader&uploader, Mail and so on.

**Comment by mystralkk** [comment]
>  something similar to the cookies popup message but for IP logging (or combine the cookie and ip messages). Is it enough to just let the user know that there IP is being logged?

In my opinion, such a popup message for IP logging is overkill.  Just describing IP logging in a site's privacy policy will be enough.

**Comment by eSilverStrike** [comment]
Sounds good.
