### ISSUE TITLE
[Bugs] template parsing restricted to files [1]

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#619]
**Reported by remy on 14 Jan 2015 09:21**

**Version:** 2.1.0

[Mantis Bugtracker #1795](http://project.geeklog.net/tracking/view.php?id=1795)

**Comment by eSilverStrike** [comment]
I am going to close this since the description is missing.

I did add a view in Geeklog 2.1.3 to the template class for feature #784 (changeset 1998b235eb3221974de7b83cbfa047f2e276c8c6) which is now used by the staticpages plugin. It allows you to pass the contents you want to be parsed by the template class. These contents can be located in a variable and not a file.
