### ISSUE TITLE
switchlang.php does not work in topic top page

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#801]
switchlang.php does not work in topic top page.

Japanese top page:
https://demo.geeklog.jp/index.php/topic/home_ja
English top page:
https://demo.geeklog.jp/index.php/topic/home_en

switchlang.php does not work in topic top page 
https://demo.geeklog.jp/switchlang.php/en
https://demo.geeklog.jp/switchlang.php/ja

**Comment by ivywe** [comment]
COM_getLanguageFromURL() can't return correct topic top lang id.

**Comment by eSilverStrike** [comment]
Article, Topics, and Staticpages (and maybe other third party plugins) support multiple languages. If the 
 page the user is already on is in a specific language there may not be a page for it in the new language they are switching to, or the user could not have access to it. 

If this problem exists then we will default to the home page. For plugins (like the staticpage) there may be no way to figure out if another page exists (I have to check in on this). In this case the webmaster will have to ensure for all languages offered on the site there is a matching page for it. If not then the user will most likely get a 404 error.

**Comment by eSilverStrike** [comment]
Looking into this further I don't see an easy way to handle this issue. It can happen not only with topics but articles, staticpages and other plugins that support multiple languages but the user only creates content in one language.

There is no easy way to determine when looking at the previous url when switching languages if we need to be worried about it being a multi language article and if the user has access to the switch language version of the article or if it even exists. This problem is worse when dealing with plugins as since we only have the url there is no easy way to figure out if it is a plugin and what the id is, and even if we need to be worried about it supporting multiple languages.

So as a work around I have added the config option switchlang_homepage which if true tells the switch language block to always redirect to the homepage after a language switch. Admin would set this to true if they have language specific content on the site that doesn't exist in any other language.
