### ISSUE TITLE
URL Routing Enabled and Article edit link Missing URL

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Core/geeklog#932]
Bug report from alb3rt. Initially reported here: https://www.geeklog.net/forum/viewtopic.php?showtopic=96991

I enabled url routing in my new site, this works fine but I found a little error. The variable {edit_url} it is empty when you read full article, for example:

http://site.net/article/my-article

Even with "root" user. In the file ~system/lib-article.php line 571 I find:

```
        if (($index != 'p') && SEC_hasRights('story.edit') &&
            ($story->checkAccess() == 3) &&
            (TOPIC_hasMultiTopicAccess('article', $story->DisplayElements('sid')) == 3)
        ) { ...

``` 

The conditions are not met `( SEC_hasRights = empty, $story->checkAccess = 2, TOPIC_hasMultiTopicAccess = 2)`.

Can it be a bug? I can't find a way to enable the edit-url button with the url routing enabled. I insist, this happens when you read full article.

Best regards

**Comment by eSilverStrike** [comment]
Tested and appears to work fine. If any more info comes to light on how to reproduce this issue we can reopen.

**Comment by eSilverStrike** [comment]
alb3rt >> I enabled a virtual machine with ubuntu server 16.04 + php 7.0 (FPM/FastCGI) y MariaDB but I can't run "rewrite" correctly.

**Comment by ramosgt** [comment]
I have duplicated the error, it happens when you login to the site using the form that appears in the admin section.

`site.com/admin/`

When doing it in this way the cookie "password" is not established.

If you enter from: `site.com/users.php`

Everything seems to work correctly.

However, I have enabled several virtual servers and the rewrite completely fails again, having the same configuration (same operating system, same versions of php, mysql, apache), using phpinfo () in both they show me same configuration however it still does not work, I think the lack of a module or some additional configuration is missing, but I can not find what it is. In the apache configuration I have enabled "rewrite" and "headers".

- alb3rt

**Comment by ramosgt** [comment]
Solved, I posted my experience in the geeklog forum.

**Comment by eSilverStrike** [comment]
Does the login error happen under the admin only happen with url routing enabled? (or just url rewrite)

**Comment by ramosgt** [comment]
When login from `site/admin`, there is no "password" cookie, but the icon error only occurs if url routing is active.

I do not know if it has something to do but in: `~/system/classes/router.class.php` line 87:
`//Add the current cookies.  Otherwise, session will be lost.
        foreach ($_COOKIE as $key => $value) {
...`

**Comment by eSilverStrike** [comment]
@mystralkk - This is something we should check once the new session class is finished #828

**Comment by eSilverStrike** [comment]
I've tested this with URL Routing enabled (both modes) and the article edit icon comes up fine if I log in via the admin directory. I checked the cookies and the "geeklog" one along with the "GLSESSION" are both their logging in either way. I am assuming that the implementation of the new session class fixed this.
