### ISSUE TITLE
switchlang.php does not work at staticpage.php and other plugins

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#934]
switchlang.php work at only topic pages.

switchlang.php dose not work at staticpage.php and other plugins

**Comment by eSilverStrike** [comment]
Item Type template variable name was incorrect in switchlanguage.thtml template file. "t" needed to be capitalized.

Change:
`<input type="hidden" name="itemtype" value="{itemtype}"{XHTML}>`
to
`<input type="hidden" name="itemtype" value="{itemType}"{XHTML}>`

**Comment by eSilverStrike** [comment]
Found a further issue which would prevent switch language block working for staticpages when the staticpage plugin was installed at v1.7.0 (not upgraded). 

```
DELETE FROM `gl_conf_values` WHERE type='@hidden';

INSERT INTO `gl_conf_values` (`name`, `value`, `type`, `group_name`, `default_value`, `subgroup`, `selectionArray`, `sort_order`, `tab`, `fieldset`) VALUES('langurl_article', 'a:3:{i:0;s:0:"";i:1;s:11:"article.php";i:2;s:5:"story";}', '@hidden', 'Core', 'a:3:{i:0;s:0:"";i:1;s:11:"article.php";i:2;s:5:"story";}', 7, 1, 1830, 31, 31);
INSERT INTO `gl_conf_values` (`name`, `value`, `type`, `group_name`, `default_value`, `subgroup`, `selectionArray`, `sort_order`, `tab`, `fieldset`) VALUES('langurl_staticpages', 'a:3:{i:0;s:11:"staticpages";i:1;s:9:"index.php";i:2;s:4:"page";}', '@hidden', 'Core', 'a:3:{i:0;s:11:"staticpages";i:1;s:9:"index.php";i:2;s:4:"page";}', 7, 1, 1830, 31, 31);
INSERT INTO `gl_conf_values` (`name`, `value`, `type`, `group_name`, `default_value`, `subgroup`, `selectionArray`, `sort_order`, `tab`, `fieldset`) VALUES('langurl_topic', 'a:3:{i:0;s:0:"";i:1;s:9:"index.php";i:2;s:5:"topic";}', '@hidden', 'Core', 'a:3:{i:0;s:0:"";i:1;s:9:"index.php";i:2;s:5:"topic";}', 7, 1, 1830, 31, 31);
```

**Comment by eSilverStrike** [comment]
With new fix Tested for default URLs, URL Rewrite, and URL Routing (both with and without index.php)
Tested for Articles, Topics, and Static Pages( should work with all plugins that support multiple languages). If an alternate language item exists when switching language it will load that item.

Function _getLanguageInfoFromURL that does most of the work loads several times for some reason on a page load which alters the current page URL for some reason (ie the URL Routing URL will fall back to the default URL). I have a feeling this happens because of the URL class. Not sure and had already spent a number of hours on this. So I made the function work with the current situation
