### ISSUE TITLE
[Feature Requests] add limit size for log files 

### ISSUE THREAD

**Issue by ivywe** [Geeklog-Core/geeklog#942]
Log files grow endlessly.
I want to determine the maximum value.

**Comment by eSilverStrike** [comment]
There are  option s for this like

https://www.php.net/manual/en/function.ftruncate.php#103591

Which will truncate  and actually search for a newline to avoid cutting the file in a middle of a record. The problem is it can be expensive which may be an issue if for example your site is getting hammered by a bot with 404 errors...

Another option could be to only do this check once a day or something...

**Comment by mystralkk** [comment]
Added this feature with change set 9f55b9e.
Usage: calling Geeklog\Log::truncate('error.log', $logFileSizeInBytes);
from, say, CUSTOM_runScheduledTask().
