### ISSUE TITLE
Change the installer in such a way that it only installs/upgrades Geeklog core, without handling plugins

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#957]
Currently, the installer installs/updates Geeklog core AND installs/updates plugins at the same time.  This makes the installer so complicated that it is hard to debug.  In addition, plugins that are not fully tested could cause errors, which beginners cannot easily solve.

Thus, I suggest that we change the installer in such a way that it only installs/upgrades Geeklog core, without handling plugins.  After having installed/upgraded core, users can more safely install/upgrade plugins.

**Comment by eSilverStrike** [comment]
@dhaun thoughts? (since you have dealt with the installer a lot, but a while ago)

I agree, the installer is a real pain to debug. We have multiple functions in the install that do almost the same thing which adds to the confusion. Lots of old legacy code.

Personally I don't want to touch something that isn't broken but maybe it would be a good idea at some point to change it.

I think the reason it was done this way is that if Geeklog had a major code change in how plugins are handled it was easier to handle the plugin upgrade after each version upgrade of Geeklog. 

Pros
- Installer would not fail on a plugin upgrade making for much smoother Geeklog upgrades
- No duplicate plugin upgrade code in the installer, would just use Geeklog's own upgrade code

Cons
- Now it is a 2 step process to upgrade Geeklog
- Plugins can possibly break Geeklog if not upgraded after a major change in Geeklog

Wondering if after the Geeklog install process we go to the Geeklog Plugins page to initiate the plugin upgrade process (with a message, etc), We could even show the users as we cycle through each plugin upgrade (and fail gracefully if possible) and then end with the finish Geeklog install/upgrade message.

During the Geeklog upgrade we will probably have to disable all plugins just to be safe. We may also want to add an option in the install to keep plugins disabled that didn't actually upgrade at the end.

Maybe if/when we do this we remove all the legacy upgrade code and scripts from the install, and bump the version of Geeklog to 3.0. This would make things much easier to code (and remove the mistakes of the past). It would also mean that if someone is upgrading from an old version of Geeklog they would first have to upgrade using whatever the last version of the installer we support, and then run the current installer to finish the upgrade.

**Comment by eSilverStrike** [comment]
Also see #860

**Comment by eSilverStrike** [comment]
Plugin configs also have an issue loading during migration process. See https://github.com/Geeklog-Core/geeklog/commit/2289658447c61e4cf1cd5cc872323b72453c042e for the temp fix with XMLSitemap

**Comment by mystralkk** [comment]
Fixed with change set 2313dd4.

**Comment by eSilverStrike** [comment]
Expanding on my thoughts above after running the installer upgrade a few times.

I think we need maybe continue on the upgrade plugin process if needed within Geeklog somehow after the installer is finished. 

OR at least take the user to the plugins page after the installer message if it detects some plugins need to be updated.

AND/OR maybe we shouldn’t allow plugins to run at all if the File Version and Data version are not equal? As in some cases obviously a plugin running with mismatched versions could completely break the site.  This would require some changes to Geeklog as of right now you can't update a plugin that has been deactivated.

For example with the latest upgrade since the polls plugin ips are anominized my Geeklog homepage crashes because while the files have been updated to the latest version the data is not so it is missing the seq table column. Most users would not realize why this has happened and get frustrated.

**Comment by mystralkk** [comment]
After lots of fresh install and upgrading, I reverted the changes I made to the installer.

> Con: 2. Plugins can possibly break Geeklog if not upgraded after a major change in Geeklog

What you said really makes sense.
