### ISSUE TITLE
Move Emergency Rescue Tool from admin/install/ to admin/ directory

### ISSUE THREAD

**Issue by mystralkk** [Geeklog-Core/geeklog#958]
It is more convenient if you can use the Emergency Rescue Tool after having deleted the admin/install/ directory.

**Comment by eSilverStrike** [comment]
@mystralkk Do you want to add this to v2.2.1 or leave it for the next version of Geeklog?

**Comment by mystralkk** [comment]
I don't mind leaving it for the next version of Geeklog.

**Comment by mystralkk** [comment]
Relocated Emergency Rescue Tool from admin/install. to admin/ with change set eef65d1

**Comment by eSilverStrike** [comment]
Hmm are we leaving a potential security issue here since rescue.php doesn't automatically get deleted now when the install gets deleted.

The Root user may not realize it needs to be deleted.

I think it makes sense to add a System Message to the homepage and Command and Control home that tells the root user that if rescue.php exists, it needs to be deleted. This can be added to the checks already in place for the install directory and running the Security Test (maybe these messages should appear on both the homepage and Command and Control for increased visibility). Maybe even include something eye catching beside the command and control menu item in the admin block when a security issue is detected so root admins realize they should visit Command and Control to see what the problem is.

This feature also could work for part of the problem we have in issue #957 where we need to notify Root users that plugins need the update function to run.

Does that make sense @mystralkk ?

**Comment by mystralkk** [comment]
It seems to me that most users are not aware the location of Emergency Rescue Tool has changed, so they are unlikely to remove it after installing or upgrading.  I will put the tool back to admin/install.  How about this @eSilverStrike ?

**Comment by eSilverStrike** [comment]
That would solve the problem easier than running an extra check for it in Geeklog (like the check we do for the install).

**Comment by mystralkk** [comment]
Relocated Emergency Rescue Tool again from admin/ to admin/install/ directory
